name: Optic CI Template
description: | 
  A template for running Optic CI rules against your OpenAPI files.
  Fork this repository, and add your rules under src/ruleset.
  For more information join the beta at https://www.useoptic.com/

inputs:
  file:
    description: The OpenAPI file to evalute in this PR.
    required: true
  optic_token:
    description: The Optic Token. Note, GitHub Secrets must be explicitly passed to composite actions
    required: false
  github_token:
    description: the GITHUB_TOKEN environment varibale for your current workflow, used to post a GitHub comment. Note, GitHub Secrets must be explicitly passed to composite actions
    required: false
  ruleset:
    deprecationMessage: This value is no longer used.
    description: DEPRECATED - This value is no longer used.
    required: false
    default: default

runs:
  using: composite
  steps:
      - name: Setup optic-ci
        run: |
          echo "::group::Setup"
          npm install
          echo "::endgroup::"
        shell: bash
      - name: Generate GitHub Context
        run: echo "$GITHUB_CONTEXT" > ./ci-context.json
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        shell: bash
      - name: Optionally enable Optic Cloud Changelogs
        run: |
          if [[ -n ${OPTIC_TOKEN} ]]; then
          echo "Optic Cloud Changelog token found: enabling upload"
          echo "OPTIC_CI_FLAGS=--upload-results" >> $GITHUB_ENV
          fi
        shell: bash
        env:
          OPTIC_TOKEN: ${{ inputs.OPTIC_TOKEN }}
      - run: >-
          npx optic-ci compare
          --from ${{ github.event.pull_request.base.sha }}:${{ inputs.file }}
          --to ${{ github.event.pull_request.head.sha }}:${{ inputs.file }}
          ${OPTIC_CI_FLAGS}
        env:
          FORCE_COLOR: "2"
          OPTIC_TOKEN: ${{ inputs.OPTIC_TOKEN }}
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
          OPTIC_ENV: staging
        shell: bash
