name: Optic CI Template
description: |
  A template for running Optic CI rules against your OpenAPI files.
  Fork this repository, and add your rules under src/ruleset.
  For more information join the beta at https://www.useoptic.com/

inputs:
  file:
    description: The OpenAPI file to evalute in this PR.
    required: true
  ruleset:
    description: The ruleset to apply to OpenAPI changes.
    required: false
    default: default
  optic_token:
    description: The optic token to upload your changelog
    required: true
  github_token:
    description: Token for commenting on your PR
    required: true

runs:
  using: composite
  steps:
    - name: Setup
      run: |
        echo "::group::Setup"
        yarn install
        yarn build
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: >-
        node $GITHUB_ACTION_PATH/build/index.js compare
        --from ${{ github.event.pull_request.base.sha }}:${{ inputs.file }}
        --to ${{ github.event.pull_request.head.sha }}:${{ inputs.file }}
        --ruleset ${{ inputs.ruleset }}
        --create-file
      env:
        FORCE_COLOR: 2
      shell: bash
    - run: >-
        echo $GITHUB_CONTEXT > ./ci-context.json
      env:
        FORCE_COLOR: 2
      shell: bash
    - run: >-
        OPTIC_TOKEN=${{ inputs.optic_token }} node $GITHUB_ACTION_PATH/build/index.js upload
          --from ${{ github.event.pull_request.base.sha }}:${{ inputs.file }}
          --to ${{ github.event.pull_request.head.sha }}:${{ inputs.file }}
          --provider github
          --ci-context ./ci-context.json
          --compare ./compare-output.json
      env:
        FORCE_COLOR: 2
      shell: bash
    - run: >-
        OPTIC_TOKEN=${{ inputs.github_token }} node $GITHUB_ACTION_PATH/build/index.js github-comment
          --provider github
          --ci-context ./ci-context.json
          --upload ./upload-output.json
          --token ${{ inputs.GITHUB_TOKEN }}
      env:
        FORCE_COLOR: 2
      shell: bash
