name: Optic CI Template
description: | 
  A template for running Optic CI rules against your OpenAPI files.
  Fork this repository, and [add your own rules](link).
  For more information check out the [Readme](link).

inputs:
  file:
    description: The OpenAPI file to evalute in this PR.
    required: true
  ruleset:
    description: The ruleset to apply to OpenAPI changes.
    required: false
    default: default

runs:
  using: composite
  steps:
    - run: yarn install
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: yarn build
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: chmod a+x build/index.js
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: >-
        $GITHUB_ACTION_PATH/build/index.js compare 
        --from  ${{ github.head_ref }}:${{ inputs.file }}
        --to  ${{ github.ref }}:${{ inputs.file }}
        --ruleset ${{ inputs.ruleset }}
      shell: bash