name: Optic CI example workflow definition

on: [ push, workflow_dispatch ]

jobs:
  optic-ci:
    name: Optic API Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Optic cli
        uses: LouManglass/optic-ci-starter-1@ci-update
        with:
          file: openapi.yaml
          optic_token: foo
          github_token: bar